version: 2
updates:
  - package-ecosystem: "npm"          # covers pnpm via package.json + pnpm-lock.yaml
    directory: "/"
    schedule: { interval: "daily" }
    open-pull-requests-limit: 10
    labels: ["dependencies","automerge:disabled"]

  - package-ecosystem: "poetry"
    directory: "/"
    schedule: { interval: "daily" }
    open-pull-requests-limit: 10
    labels: ["dependencies","automerge:disabled"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "daily" }
    labels: ["dependencies","automerge:disabled"]
