version: 2
updates:
  # Keep Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Node (dashboard) – works with pnpm lock via npm ecosystem
  - package-ecosystem: "npm"
    directory: "/apps/dashboard"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: increase

  # Python – use supported 'pip' ecosystem (will no-op if no requirements files yet)
  - package-ecosystem: "pip"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/apps/traderd"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/packages/common"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Terraform modules
  - package-ecosystem: "terraform"
    directory: "/infra/terraform"
    schedule:
      interval: "daily"

  # Dockerfiles at repo root
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
