name: Secret Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: "--verbose --redact --no-banner"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-review:
    name: dependency-review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependency review (GitHub)
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          deny-licenses: MIT-0 # (example denylist; adjust later)
          warn-only: false
