name: Secret Scan

on:
  pull_request: { branches: [ main] }
  push: { branches: [ main ] }

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # Default behavior scans the working tree; token required on PRs
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-review:
    if: ${{ github.event.repository.private == false }}
    name: dependency-review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
