name: Secret Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    permissions:
      contents: read        # sufficient for scanning the tree
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Run Gitleaks (scan working tree)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --redact --no-banner --exit-code 1

  dependency-review:
    if: ${{ github.event.repository.private == false }}
    name: dependency-review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependency review (GitHub)
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
