name: Terraform Validate

on:
  push:
    paths: ["infra/terraform/**", ".github/workflows/terraform-validate.yml"]
  pull_request:
    paths: ["infra/terraform/**", ".github/workflows/terraform-validate.yml"]

jobs:
  fmt_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive
      - name: Terraform init (no backend)
        working-directory: infra/terraform
        run: terraform init -backend=false
      - name: Terraform validate
        working-directory: infra/terraform
        run: terraform validate -no-color
