name: Terraform Validate
permissions:
  contents: read

on:
  push:
    paths: ["infra/terraform/**", ".github/workflows/terraform-validate.yml"]
  pull_request:
    paths: ["infra/terraform/**", ".github/workflows/terraform-validate.yml"]

jobs:
  fmt_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive
      - name: Terraform init (no backend)
        working-directory: infra/terraform
        run: terraform init -backend=false
      - name: Terraform validate
        working-directory: infra/terraform
        run: terraform validate -no-color
